### ISSUE TITLE
Light appears at certain distance, regardless of sun position

### ISSUE THREAD

**Issue by ghost** [Its-Just-Luci/EVO#5] opened 2021-03-25 23:19 UTC
Towards the horizon, when outside of the atmosphere, a certain distance away lights up - regardless of if the sun should be lighting up that area. In the screenshot, the sun is much further down, and shouldn't be lighting up the horizon.
https://imgur.com/8ZyXpXH

**Comment by Its-Just-Luci** [comment] 2021-03-30 03:45
yeah... this is a known issue, I am unaware of the cause other than that it is scatterer in some capacity

**Comment by Its-Just-Luci** [comment] 2021-05-21 19:46
I'm about to drop RSSVE's earth scatterer configs into my game, see if that helps. I'll keep you posted @Victoneux

**Comment by Its-Just-Luci** [comment] 2021-06-10 21:30
ok, so long story short, scatterer is borked at the moment, regardless of if you chose to use RSSVE, EVO or RVE64k. The latest versions of scatterer seem to just hate real scale planetary bodies, so while this is a bug, it's not my bug so I will be closing this Issue

**Closed as completed by Its-Just-Luci** 2021-06-10 21:30 UTC
Labels: WontFix, Not an Issue
