### ISSUE TITLE
Sunset clouds appearing blue & missing sunflair.

### ISSUE THREAD

**Issue by jackwrichards** [Its-Just-Luci/EVO#6] opened 2021-03-25 23:21 UTC
![image](https://user-images.githubusercontent.com/26103772/112555721-f70e2c00-8d85-11eb-94cf-3aefaa2140c5.png)

TUXF is off. 

I'm running
the latest EVO (0.2)
the latest EVE (1.8.0-2): https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases
the latest scatterer (0.0723): https://github.com/LGhassen/Scatterer/releases/tag/0.0723

**Comment by jackwrichards** [comment] 2021-03-25 23:31
![image](https://user-images.githubusercontent.com/26103772/112556459-80722e00-8d87-11eb-94f4-f8b5b3d52010.png)

**Comment by Its-Just-Luci** [comment] 2021-03-26 18:31
This is definitely an interesting one... what KSP version are you running?

**Comment by Its-Just-Luci** [comment] 2021-03-30 03:41
@Arodoid 
ok... another user was reporting green clouds when they had RSSVE installed. Do you have RSSVE or RVE64k installed? If so that is likely the cause also please list ksp version as the scatterer you are using is marked as incompatible with ksp versions below 1.9.0

**Comment by Its-Just-Luci** [comment] 2021-05-21 19:45
Issue has been open since march with no reply, being that I haven't heard if the issue is solved I will assume it to be

**Closed as completed by Its-Just-Luci** 2021-05-21 19:45 UTC
Labels: bug
